name: iot2050_CI

on: [push]

jobs:
  bootloaders:
    name: Bootloaders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Basic
        run: ./kas-container build kas-iot2050-boot-basic.yml
      - name: Advanced
        run: ./kas-container build kas-iot2050-boot-advanced.yml
      - name: Archive bootloaders
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
          
  images:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Example image
        run: ./kas-container build kas-iot2050-example.yml
      - name: Upload example image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image
          path: build/tmp/deploy/images/iot2050/iot2050-image-example-isar-iot2050.wic.img*
      - name: RT example image
        run: ./kas-container build kas-iot2050-example.yml:kas/opt/preempt-rt.yml
      - name: Upload RT example image
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-example-image-rt
          path: build/tmp/deploy/images/iot2050/iot2050-image-example-isar-iot2050.wic.img*
    
  sdk:
    name: Sdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: iot2050_sdk
        run: ./kas-container build kas/iot2050.yml:kas/opt/sdk.yml:kas/opt/package-lock.yml
      - name: Upload sdk
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-sdk
          path: build/tmp/deploy/images/iot2050/sdk-isar-arm64.tar.xz*
     

  